### ISSUE TITLE
The problem with sending messages from ROS2 to Fast-RTPS

### ISSUE THREAD

**Issue by gek40** [eProsima/SOSS-DDS#41]
Hello!
I'm trying make communication via Fast-RTPS and ROS2 with help SOSS-DDS.
My trouble look like [this](https://github.com/eProsima/SOSS-DDS/issues/20#issue-508326419) issue. I tried the recommendations but nothing helped
I have the Fast-RTPS with branch origin/release/1.7.2
I made the idl message:
```
struct std_msgs__String
{
   string data;
};
```
and generated a code with help fastrtpsgen. My code based on DynamicHelloWorldExample (https://github.com/gek40/dds_experiments/tree/master/DynamicStdMsgsString)
When I send a message from the Fast-RTPS publisher all is ok. Subscriber print this:
```
Starting 
Subscriber running. Please press enter to stop the Subscriber
Participant Dynm_StdMsgsString_pub discovered

onPublisherDiscovery: typeName = std_msgs__String, topicName = StdMsgsString_Topic
Subscriber matched
onNewDataMessage from StdMsgsString_Topic with type std_msgs__String
!!! Message: String from Fast-RTPS RECEIVED
Subscriber unmatched

onPublisherDiscovery: typeName = std_msgs__String, topicName = StdMsgsString_Topic
Participant Dynm_StdMsgsString_pub removed

```
But when I send a message from ROS2 topic through SOSS subscriber print:
```
Starting 
Subscriber running. Please press enter to stop the Subscriber
Participant RTPSParticipant discovered
Participant soss_ros2 discovered

onPublisherDiscovery: typeName = std_msgs__String, topicName = StdMsgsString_Topic
Subscriber matched
Participant _ros2cli_publisher_std_msgs_String discovered
Participant _ros2cli_publisher_std_msgs_String removed

onPublisherDiscovery: typeName = std_msgs__String, topicName = StdMsgsString_Topic
Participant soss_ros2 removed
Participant RTPSParticipant removed
```
SOSS print this:
```
[soss-dds]: participant not provided in configuration file. UDP default participant will be created.
[soss-dds]: configured!
[soss-dds]: publisher created. topic: StdMsgsString_Topic, type: std_msgs/String
[soss-dds][publisher]: matched (StdMsgsString_Topic) 
```
This seems like a problem in the communication of ROS2 and SOSS, because SOSS does not respond to the publication in the ROS topic.

Some ideas on this?
Thanks!

_Originally posted by @gek40 in https://github.com/eProsima/SOSS-DDS/issues/20#issuecomment-575631283_

**Comment by gek40** [comment]
I found the problem. I'm using ROS2 Dashing. When I installed a new Ubuntu with ROS2 Crystal, communication began to work.
ROS2 Crystal is using Fast-RTPS v 1.7.2
ROS2 Dashing is using Fast-RTPS v 1.8.0

I know that SOSS-DDS works with Fast-RTPS 1.7.2. It turns out that ROS topics should use  1.7.2 version too. What is the significant difference between Fast-RTPS 1.7 and 1.8? Communication via Fast-RTPS 1.7.2 and Fast-RTPS 1.8.0 nodes (without SOSS) works in both direction. Maybe someone can tell why this is happening? I would like to use SOSS with ROS dashing. But I can’t find the reasons why this works with 1.7.2 and does not work with 1.8.0.

Communication DDS -> ROS2 always works well. But using ROS2 dashing ROS messages are ignored. At the launch moment, SOSS subscribes to ROS topics correctly. ROS2 detects the connection. But messages from ROS are simply ignored. I found a prototype for ROS2 subscribers placed in soss/packages/ros2/resources/convert__msg.cpp.em. I added output to the file at the beginning of the functions. ROS2 callback is simply not called. Maybe there are hidden details that can be explored? How I can debug SOSS for searching problem?

I will be glad of any help! Thanks!

**Comment by richiware** [comment]
Fast-RTPS 1.8.2, the version used by current ROS2 Dashing, introduced an incompatibility with other versions. This was fixed in Fast-RTPS 1.8.3, at least against Fast-RTPS 1.9.x serie. We didn't test against Fast-RTPS 1.7.2.

Did you compile ROS2 Dashing? Could you use Fast-RTPS 1.8.3 instead of 1.8.2 and test it?

**Comment by gek40** [comment]
Ok, Thanks!
I used ROS2 Dashing from binary packages before. 
Now I built ROS2 Dashing from sources with other Fast-RTPS versions.
Fast-RTPS v1.7.2 - compile errors from rmw_fastrtps. It's has different code naming in some variables
Fast-RTPS v1.8.3 - compile is fine. But the problem remains the same.
Fast-RTPS v1.9.4 - compile is fine. Communication ROS2 <-> Fast-RTPS node works in both directions!

Eventually: 
ROS2 Dasing with Fast-RTPS v1.9.4 built from source (install path: ~/ros2_dashing/install/fastrtps/lib) 
Fast-RTPS v.1.7.2 built from source (install path: /usr/local/lib)
SOSS-DDS built with help colcon. 
It's working for me.

@richiware, thanks for the help!

I think this issue can be closed.
